name: Get News

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  news:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Setup Chrome Driver
        uses: nanasess/setup-chromedriver@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Chrome Driver Path
        run: |
          which chromedriver
          echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV

      - name: Run Scraping Script
        run: |
          python scrape.py

      - name: Copy News to Readme
        run: |
          cp README-base.md README.md
          echo -e "\n## $(date '+%A %B %d %Y')\n\n" >> README.md
          cat news.md >> README.md

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet --cached HEAD || git commit -m "Update News"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
